Proje/Proje/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Proje.DataAccessLayer;
using Proje.Models;
using Proje.Models.DBEntities;

namespace Proje.Controllers
{
    public class CompanyController : Controller
    {
        private readonly CompanyDbContext _context;
        public CompanyController(CompanyDbContext context) 
        { 
            this._context = context;
        }

        [HttpGet]
        public IActionResult Index()

        {
            var companies = _context.Companies.ToList();
            List<CompanyViewModel> companylist = new List<CompanyViewModel>();
            if (companies != null)
            {
                
                foreach(var company in companies)
                {
                    var ComapanyViewModel = new CompanyViewModel()
                    {
                        Id = company.Id,
                        CompanyName = company.CompanyName,
                        CompanyStatus = company.CompanyStatus,
                        SectorID = company.SectorID,
                        EntegrationID = company.EntegrationID,
                        Contract_Start = company.Contract_Start,
                        Contract_End = company.Contract_End,
                       Authorized = company.Authorized,

                    };
                    companylist.Add(ComapanyViewModel);

                }
                return View(companylist);
            }
            return View(companylist);
        }
        [HttpGet]
        public IActionResult Add() 
        {

            return View();
        }

        [HttpPost]
        public IActionResult Add(CompanyViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var company = new Company()
                    {
                        CompanyName = Proje.CompanyName,
                        CompanyStatus = Proje.CompanyStatus,
                        SectorID = Proje.SectorID,
                        EntegrationID = Proje.EntegrationID,
                        Contract_Start = Proje.Contract_Start,
                        Contract_End = Proje.Contract_End,
                        Authorized = Proje.Authorized,

                    };
                    _context.Companies.Add(company);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Company addded succesfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Error Message"] = " Model data is not valid.";
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;
                return View();
            }
        }

        [HttpGet]

        public IActionResult Edit(int Id) {

            try
            {
                var company = _context.Companies.SingleOrDefault(x => x.Id == Id);
                if (company != null)
                {
                    var companyView = new CompanyViewModel()
                    {
                        Id = company.Id,
                        CompanyName = company.CompanyName,
                        CompanyStatus = company.CompanyStatus,
                        SectorID = company.SectorID,
                        EntegrationID = company.EntegrationID,
                        Contract_Start = company.Contract_Start,
                        Contract_End = company.Contract_End,
                        Authorized = company.Authorized,


                    };
                    return View(companyView);
                }
                else
                {
                    TempData["Error Message"] = " Company Details not available";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult Edit(CompanyViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var company = new Company()
                    {
                        Id = Proje.Id,
                        CompanyName = Proje.CompanyName,
                        CompanyStatus = Proje.CompanyStatus,
                        SectorID = Proje.SectorID,
                        EntegrationID = Proje.EntegrationID,
                        Contract_Start = Proje.Contract_Start,
                        Contract_End = Proje.Contract_End,
                        Authorized = Proje.Authorized,
                    };
                    _context.Companies.Update(company);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Company details updated successfully!";
                    return RedirectToAction("Index");

                }
                else
                {
                    TempData["Error Message"] = "Model data is invalid";
                        return View();
                }
            }
            catch (Exception ex)
            {

                TempData["Error Message"] = ex.Message;

                return View();
            }


        }
        [HttpGet]

        public IActionResult Delete(int Id)
        {

            try
            {
                var company = _context.Companies.SingleOrDefault(x => x.Id == Id);
                if (company != null)
                {
                    var companyView = new CompanyViewModel()
                    {
                        Id = company.Id,
                        CompanyName = company.CompanyName,
                        CompanyStatus = company.CompanyStatus,
                        SectorID = company.SectorID,
                        EntegrationID = company.EntegrationID,
                        Contract_Start = company.Contract_Start,
                        Contract_End = company.Contract_End,
                        Authorized = company.Authorized,


                    };
                    return View(companyView);
                }
                else
                {
                    TempData["Error Message"] = " Company Details not available";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("Index");
            }

        }

        [HttpPost]

        public  IActionResult Delete(CompanyViewModel model)
        {
            try
            {
                var company = _context.Companies.SingleOrDefault(x => x.Id == model.Id);
                if (company != null)
                {
                    _context.Companies.Remove(company);
                    _context.SaveChanges();
                    TempData["Success Message"] = "Company deleted successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Error Message"] = " Company Details not available";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return View();

            }
            
        }


    }
}

Proje/Proje/Controllers/SectorController.cs
using Microsoft.AspNetCore.Mvc;
using Proje.DataAccessLayer;
using Proje.Models;
using Proje.Models.DBEntities;

namespace Proje.Controllers
{
    public class SectorController : Controller
    {
        private readonly SectorDbContext _context;
        public SectorController(SectorDbContext context) 
        { 
            this._context = context;
        }


        [HttpGet]
        public IActionResult SectorIndex()
        {
            var sectors= _context.Sectors.ToList();
            List<SectorViewModel> Sectorlist = new List<SectorViewModel>();
            if (sectors != null )
            {
                
                foreach( var sector in sectors )
                {
                    var sectorViewModel = new SectorViewModel()
                    {
                        SectorID = sector.SectorID,
                        SectorName = sector.SectorName,
                        SectorIsActive = sector.SectorIsActive,
                    };
                    Sectorlist.Add(sectorViewModel);

                }
                return View(Sectorlist);
            }
            return View(Sectorlist);
        }

        //add sector
        [HttpGet]
          public ActionResult Add() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(SectorViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Sectors = new Sector()
                    {
                       
                        SectorID = Proje.SectorID,
                        SectorName = Proje.SectorName,
                        SectorIsActive = Proje.SectorIsActive,
                       

                    };
                    _context.Sectors.Add(Sectors);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Sector addded succesfully";
                    return RedirectToAction("SectorIndex");
                }
                else
                {
                    TempData["Error Message"] = " Model data is not valid.";
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;
                return View();
            }
        }

        [HttpGet]

        public IActionResult Edit(int Id)
        {

            try
            {
                var Sector = _context.Sectors.SingleOrDefault(x => x.SectorID == Id);
                if (Sector != null)
                {
                    var SectorView = new SectorViewModel()
                    {
                       
                        SectorID = Sector.SectorID,
                        SectorName = Sector.SectorName,
                        SectorIsActive = Sector.SectorIsActive,
                        


                    };
                    return View(SectorView);
                }
                else
                {
                    TempData["Error Message"] = " Company Details not available";
                    return RedirectToAction("SectorIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("SectorIndex");
            }



        }
        [HttpPost]
        public IActionResult Edit(SectorViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Sector = new Sector()
                    {
                       
                        SectorID = Proje.SectorID,
                        SectorName = Proje.SectorName,
                        SectorIsActive = Proje.SectorIsActive,

                    };
                    _context.Sectors.Update(Sector);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Company details updated successfully!";
                    return RedirectToAction("SectorIndex");

                }
                else
                {
                    TempData["Error Message"] = "Model data is invalid";
                    return View();
                }
            }
            catch (Exception ex)
            {

                TempData["Error Message"] = ex.Message;

                return View();
            }


        }

        [HttpGet]

        public IActionResult Delete(int Id)
        {

            try
            {
                var Sector = _context.Sectors.SingleOrDefault(x => x.SectorID == Id);
                if (Sector != null)
                {
                    var SectorView = new SectorViewModel()
                    {

                        SectorID = Sector.SectorID,
                        SectorName = Sector.SectorName,
                        SectorIsActive = Sector.SectorIsActive,



                    };
                    return View(SectorView);
                }
                else
                {
                    TempData["Error Message"] = " Sector Details not available";
                    return RedirectToAction("SectorIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("SectorIndex");
            }



        }

        [HttpPost]

        public IActionResult Delete(SectorViewModel model)
        {
            try
            {
                var Sector = _context.Sectors.SingleOrDefault(x => x.SectorID == model.SectorID);
                if (Sector != null)
                {
                    _context.Sectors.Remove(Sector);
                    _context.SaveChanges();
                    TempData["Success Message"] = "Sector deleted successfully";
                    return RedirectToAction("SectorIndex");
                }
                else
                {
                    TempData["Error Message"] = " Sector Details not available";
                    return RedirectToAction("SectorIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return View();

            }

        }

    }
}

Proje/Proje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Data Platform</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company List</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Sector" asp-action="SectorIndex" >Sector</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Personal" asp-action="PersonalIndex">Personal</a></li>
                                <li><a class="dropdown-item" href="">Type</a></li>
                                <li><a class="dropdown-item" href="#">Company Responsible</a></li>
                                                    
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Proje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/customjs.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>