Proje/Proje/Models/DBEntities/Personal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Proje.Models.DBEntities
{
    public class Personal


    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
       
        public int PersonalId { get; set; }
        public string NameSurname { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }

        public string PhoneNumber { get; set; }
    }
}

Proje/Proje/Models/PersonalViewModel.cs
using System.ComponentModel;

namespace Proje.Models
{
    public class PersonalViewModel
    {

        [DisplayName("Personal ID")]
        public int PersonalId { get; set; }

        [DisplayName("Name")]
        public string NameSurname { get; set; }

        [DisplayName("Gender")]
        public string Gender { get; set; }

        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
    }
}

Proje/Proje/Controllers/PersonalController.cs
using Microsoft.AspNetCore.Mvc;
using Proje.DataAccessLayer;
using Proje.Models;
using Proje.Models.DBEntities;

namespace Proje.Controllers
{
    public class PersonalController : Controller
    {
        private readonly PersonalDbContext _context;
        public PersonalController(PersonalDbContext context)
        {
            this._context = context;
        }

        [HttpGet]
        public IActionResult PersonalIndex()

        {
            var personals = _context.Personals.ToList();
            List<PersonalViewModel> PersonalList = new List<PersonalViewModel>();
            if (personals != null)
            {

                foreach (var personal in personals)
                {
                    var PersonalViewModel = new PersonalViewModel()
                    {
                        PersonalId = personal.PersonalId,
                        NameSurname = personal.NameSurname,
                        Gender = personal.Gender,
                        Title = personal.Title,
                        PhoneNumber=personal.PhoneNumber,

                    };
                    PersonalList.Add(PersonalViewModel);

                }
                return View(PersonalList);
            }
            return View(PersonalList);
        }

        //add Personal
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(PersonalViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var personal = new Personal()
                    {

                        PersonalId = Proje.PersonalId,
                        NameSurname= Proje.NameSurname,
                        Gender= Proje.Gender,
                        Title = Proje.Title,
                        PhoneNumber= Proje.PhoneNumber,

                    };
                    _context.Personals.Add(personal);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Personal addded succesfully";
                    return RedirectToAction("PersonalIndex");
                }
                else
                {
                    TempData["Error Message"] = " Model data is not valid.";
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;
                return View();
            }
        }


        [HttpGet]

        public IActionResult Edit(int Id)
        {

            try
            {
                var personal = _context.Personals.SingleOrDefault(x => x.PersonalId == Id);
                if (personal != null)
                {
                    var PersonalView = new PersonalViewModel()
                    {

                        PersonalId = personal.PersonalId,
                        NameSurname = personal.NameSurname,
                        Gender = personal.Gender,
                        Title = personal.Title,
                        PhoneNumber = personal.PhoneNumber,




                    };
                    return View(PersonalView);
                }
                else
                {
                    TempData["Error Message"] = " Personal Details not available";
                    return RedirectToAction("PersonalIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("PersonalIndex");
            }



        }


        [HttpPost]
        public IActionResult Edit(PersonalViewModel Proje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var personal = new Personal()
                    {

                        PersonalId = Proje.PersonalId,
                        NameSurname = Proje.NameSurname,
                        Gender = Proje.Gender,
                        Title = Proje.Title,
                        PhoneNumber = Proje.PhoneNumber,

                    };
                    _context.Personals.Update(personal);
                    _context.SaveChanges();
                    TempData["Success Message"] = " Personal details updated successfully!";
                    return RedirectToAction("PersonalIndex");

                }
                else
                {
                    TempData["Error Message"] = "Model data is invalid";
                    return View();
                }
            }
            catch (Exception ex)
            {

                TempData["Error Message"] = ex.Message;

                return View();
            }


        }


        [HttpGet]

        public IActionResult Delete(int Id)
        {

            try
            {
                var personal = _context.Personals.SingleOrDefault(x => x.PersonalId == Id);
                if (personal != null)
                {
                    var PersonalView = new PersonalViewModel()
                    {

                        PersonalId = personal.PersonalId,
                        NameSurname = personal.NameSurname,
                        Gender = personal.Gender,
                        Title = personal.Title,
                        PhoneNumber = personal.PhoneNumber,




                    };
                    return View(PersonalView);
                }
                else
                {
                    TempData["Error Message"] = " Personal Details not available";
                    return RedirectToAction("PersonalIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return RedirectToAction("PersonalIndex");
            }



        }

        public IActionResult Delete(PersonalViewModel model)
        {
            try
            {
                var personal = _context.Personals.SingleOrDefault(x => x.PersonalId == model.PersonalId);
                if (personal != null)
                {
                    _context.Personals.Remove(personal);
                    _context.SaveChanges();
                    TempData["Success Message"] = "Personal deleted successfully";
                    return RedirectToAction("PersonalIndex");
                }
                else
                {
                    TempData["Error Message"] = " Personal Details not available";
                    return RedirectToAction("PersonalIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;

                return View();

            }

        }

    }
}

Proje/Proje/Views/Personal/Add.cshtml
@model Proje.Models.PersonalViewModel

@{
    ViewData["Title"] = "Add Personal";
    var errormessage = TempData["Error Message"]?.ToString();

}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errormessage))
{
    <div class="alert alert-succes">
        <strong>Success! </strong>@errormessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert">  </button>
    </div>

}
<form action="Add" method="post" autocomplete="off">
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="NameSurname" />
        <span asp-validation-for="NameSurname" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Gender</label>
        <input type="text" class="form-control" asp-for="Gender" />
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Phone Number</label>
        <input type="text" class="form-control" asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>


    <div class="d-grid">
        <button type="submit" class="btn-btn-primary">Submit</button>

    </div>


</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
 }

Proje/Proje/Views/Personal/Delete.cshtml
@model Proje.Models.PersonalViewModel

@{
    ViewData["Title"] = "Delete Personal";
    var errormessage = TempData["Error Message"]?.ToString();
}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errormessage))
{
    <div class="alert alert-danger">
        <strong>Error!</strong>@errormessage
    </div>
    <button type="button" class="btn-close float-end" data-bs-dismiss="alert">  </button>
}
<form action="Delete" method="post" autocomplete="off">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="PersonalId" readonly />
    </div>

    <div class=" mb-3">
        <label class="form-label">Sector Name</label>
        <input type="text" class="form-control" asp-for="NameSurname" readonly />

    </div>

    <div class=" mb-3">
        <label class="form-label">Sector Is Active</label>
        <input type="text" class="form-control" asp-for="Gender" readonly />

    </div>

    <div class=" mb-3">
        <label class="form-label">Sector Is Active</label>
        <input type="text" class="form-control" asp-for="Title" readonly />

    </div>

    <div class=" mb-3">
        <label class="form-label">Sector Is Active</label>
        <input type="text" class="form-control" asp-for="PhoneNumber" readonly />

    </div>


    <div class="d-grid">
        <button type="submit" class=" btn btn-danger" onclik="return function('Are you sure delete company  :
        @Model.NameSurname')">
            Delete
        </button>
    </div>

</form>

Proje/Proje/Views/Personal/Edit.cshtml
@model Proje.Models.PersonalViewModel

@{
    ViewData["Title"] = "Edit Personal";
    var errormessage = TempData["Error Message"]?.ToString();
}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errormessage))
{
    <div class="alert alert-danger">
        <strong>Error!</strong>@errormessage
    </div>
    <button type="button" class="btn-close float-end" data-bs-dismiss="alert">  </button>
}
<form action="Edit" method="post" autocomplete="off">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="PersonalId" readonly />
    </div>

    <div class=" mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="NameSurname" />
        <span asp-validation-for="NameSurname" class="text-danger"></span>
    </div>

    <div class=" mb-3">
        <label class="form-label">Gender</label>
        <input type="text" class="form-control" asp-for="Gender" />
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class=" mb-3">
        <label class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class=" mb-3">
        <label class="form-label">Phone Number</label>
        <input type="text" class="form-control" asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>


    <div class="d-grid">
        <button type="submit" class=" btn btn-primary">Update</button>
    </div>

</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proje/Proje/Views/Personal/PersonalIndex.cshtml
@model List<Proje.Models.PersonalViewModel>

@{
    ViewData["Title"] = "Personal List";
    var succedmessage = TempData["Success Message"]?.ToString();
    var errormessage = TempData["Error Message"]?.ToString();
}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(succedmessage))
{
    <div class="alert alert-succes">
        <strong>Success! </strong>@succedmessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert">  </button>
    </div>

}
else if (!string.IsNullOrWhiteSpace(errormessage))
{
    <div class="alert alert-danger">
        <strong>Error! </strong>@errormessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert">  </button>
    </div>

}


<form>
    <button asp-action="add" asp-controller="Personal" class="btn btn-primary">Add Personal</button>
    <table class="table table-responsive table-hover table-bordered ">
        <thead>
            <tr class="table-active">

                <th class="text-center">ID</th>
                <th class="text-center">Name</th>
                <th class="text-center">Gender</th>
                <th class="text-center">Title</th>
                <th class="text-center">Phone Number</th>
                <th class="text-center">Action</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var personal in Model)
                {
                    <tr>
                        <td class="text-center">@personal.PersonalId</td>
                        <td class>@personal.NameSurname</td>
                        <td class="text-center">@personal.Gender</td>
                        <td class="text-center">@personal.Title</td>
                        <td class="text-center">@personal.PhoneNumber</td>

                        <td class="text-center">
                            <div class="btn btn-group-sm ">
                                <a asp-controller="Personal" asp-action="Edit" asp-route-id="@personal.PersonalId" class="btn btn-primary ">Edit</a>
                                <a asp-controller="Personal" asp-action="Delete" asp-route-id="@personal.PersonalId" class="btn btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                }

            }
            else
            {
                <tr>
                    <td colspan="6">
                        <div>
                            NO PERSONAL AVAILABLE AT THIS MOMENT!
                    </td>
                </tr>

            }
        </tbody>
    </table>
</form>